# Generated by Django 4.2.7 on 2023-11-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_rate_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='currency_type',
        ),
    ]
