# Generated by Django 4.2.7 on 2023-12-11 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_alter_contactus_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
