# Generated by Django 4.2.7 on 2023-12-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_contactus_created_contactus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='name',
        ),
    ]
