# Generated by Django 4.2.7 on 2023-12-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_remove_contactus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default='Name', max_length=64, verbose_name='Name'),
        ),
    ]
