# Generated by Django 4.2.7 on 2023-12-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_requestresponselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponselog',
            name='request_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='requestresponselog',
            name='time',
            field=models.IntegerField(),
        ),
    ]
