name: Lint

on: [pull_request]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 flake8-builtins flake8-print flake8-breakpoint
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
